module.exports = {
  plugins: [require("@trivago/prettier-plugin-sort-imports")],
  arrowParens: "avoid",
  bracketSpacing: true,
  insertPragma: false,
  jsxBracketSameLine: false,
  printWidth: 80,
  proseWrap: "preserve",
  requirePragma: false,
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "all",
  useTabs: false,
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
