name: GitHub Actions CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    name: Deploy to the World-Net
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://worlds.kenny.wtf
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - uses: actions/checkout@v2
      - name: run deploy earthfile
        run: earthly --secret GITHUB_TOKEN="${{ secrets.NEXT_PUBLIC_GITHUB_TOKEN }}" --secret PULUMI_ACCESS_TOKEN="${{ secrets.PULUMI_ACCESS_TOKEN }}" --secret AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" --secret AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" +deploy
